spring:
  datasource:
    username: postgres
    password: yoshida
    url: jdbc:postgresql://localhost:5432/UrbanSensor
    hikari:
      max-lifetime: 40000
  sql:
    init:
      mode:
      continue-on-error: true

domain:
  name: https://urban.keqing.dev/