server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 95MB
      max-request-size: 100MB
  profiles:
    active: prod

  sql:
    init:
      mode:
      continue-on-error: true

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /docs

config:
  upload-dir: uploads
  avatar-dir: avatar
  file-dir: file

