server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
  profiles:
    active: dev

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /docs

