name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[cd]')"
  
  build:
    
    needs: check
    runs-on: ubuntu-latest

    steps:
    - name: Chekout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test
      
  deploy:
  
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          pm2 stop ${{ secrets.PROJECT_CONTAINER }}
          git pull
          ./gradlew build
          pm2 start ${{ secrets.PROJECT_CONTAINER }}
